export default function Home() {
  return (
    <main>
      <h1>Lorem Ipsum</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ullamcorper, metus vestibulum maximus finibus, turpis lectus fermentum erat, interdum fermentum augue elit id sem. Vivamus eu risus tristique, bibendum ligula ac, imperdiet odio. Ut vitae ullamcorper ante. Praesent eu est sem. In semper tortor non imperdiet commodo. In suscipit velit egestas iaculis posuere. Duis mollis blandit elementum. Nulla id ligula sapien. Maecenas accumsan vehicula lectus. Nullam elementum pharetra turpis, sed ornare velit imperdiet at. Integer sagittis auctor ipsum, eu maximus felis condimentum ac.</p>
      <p>Fusce blandit enim libero, in auctor velit consequat in. Fusce in ligula nisi. Nunc in lorem viverra est ullamcorper accumsan at viverra sapien. Vivamus finibus sapien in libero ornare ullamcorper. Duis gravida imperdiet suscipit. Duis ornare accumsan nulla at sollicitudin. Maecenas at varius massa, vel molestie tortor.</p>
      <p>Duis sollicitudin accumsan lorem, in hendrerit nisl pretium sed. Nunc maximus interdum posuere. Maecenas eu dignissim ante, ornare ultricies velit. Pellentesque dapibus nulla sit amet nibh fermentum tempor. Aenean blandit eros quis arcu semper, tempus varius lacus auctor. Morbi sit amet scelerisque sapien. Integer ac dolor ac ipsum consequat sagittis id ut tortor. Nulla lobortis velit a mollis convallis.</p>
      <p>Curabitur suscipit ipsum sed elit tincidunt tincidunt. Vivamus accumsan pulvinar tellus, id fermentum turpis auctor sed. Praesent eros metus, accumsan nec odio blandit, euismod ornare sem. Morbi tincidunt vehicula dui bibendum tristique. Etiam blandit congue augue non interdum. Nunc accumsan lacus ut magna elementum, vitae sagittis sapien molestie. Donec mollis tortor quis euismod faucibus. Cras sed lorem sem. Vivamus tempus orci sem, et eleifend erat laoreet egestas. Donec faucibus vestibulum nisi, ut imperdiet nulla pellentesque ut. Duis ultricies, ex eu varius volutpat, mauris ligula lacinia augue, vel maximus leo justo non odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce gravida tempus nibh, nec fringilla mi eleifend vitae.</p>
      <p>Donec libero tellus, dignissim sed vestibulum eget, varius eu est. Vivamus consectetur elit quam, nec pellentesque nisl tristique vehicula. Nam eget mauris eget orci hendrerit mollis id eu tortor. Praesent cursus volutpat turpis. Nunc euismod rutrum tellus, non blandit massa. Donec tempor tellus id felis lobortis commodo. In malesuada malesuada scelerisque. Praesent faucibus purus ut massa viverra, quis viverra neque maximus. Morbi non tristique velit, ac interdum massa. Etiam est nulla, ullamcorper eu magna eget, porta vulputate sapien. Praesent rhoncus, ipsum et ultrices consequat, ipsum urna fringilla metus, a vulputate turpis mauris ut tellus. Integer malesuada erat vitae felis luctus lobortis sed nec mi. Donec ut posuere quam. Nam rhoncus, mi sit amet scelerisque mattis, sapien sem tempus odio, eget volutpat leo purus euismod quam.</p>
    </main>
  )
}
